### ISSUE TITLE
[Feature, Refactoring] 운동 일지 미디어 관련

### ISSUE THREAD

**Issue by guswnee00** [TrainingDiary/training-diary-backend#123]
### Description
- 운동 일지 미디어(사진, 동영상) 관련 수정 
- 동영상 썸네일 생성 및 화질 조정

### TO-DO
- [x] 영상 썸네일 생성(너비 기준 360)
- [x] 영상 화질 조정(720p)
- [x] s3 업로드 로직과 비즈니스 로직, util 분리
- [x] response dto에서 cloudfront 주소로 반환
