### ISSUE TITLE
[Feature] 운동 기록 이미지 업로드

### ISSUE THREAD

**Issue by guswnee00** [TrainingDiary/training-diary-backend#40]
### Description
운동 일지에 사진 업로드 기능 추가

### TO-DO
- 사진 업로드
    - [x] @RequestPart 사용해서 dto와 file 받기
    - [x] 존재하는 운동 일지에 대해서 사진 업로드 가능
    - [x] 이미지는 10개까지 업로드 가능
    - [x] jpeg와 png 확장자를 가진 이미지만 업로드 가능
    - [x] 썸네일 생성
    - [x] 원본 이미지와 썸네일 이미지 업로드

### API
- api/trainees/workout-sessions/photos
