### ISSUE TITLE
[Feature] 운동 일지 수정

### ISSUE THREAD

**Issue by guswnee00** [TrainingDiary/training-diary-backend#63]
### Description
운동 일지 수정 기능 추가

### TO-DO
- 운동 일지 수정
    - [x] 로그인 되어있는 트레이너 확인
    - [x] 작성된 일지가 존재하는지 확인
    - [x] 새로 수정할 운동 타입이 존재하는지 확인
    - [x] 새로 수정할 운동 기록(workout)이 존재하는지 확인
    - [x] `WorkoutSessionResponseDto` 반환

### API
- PUT `api/workout-sessions`
